## Random Numbers

#### Generate a random integer from 0 to 100

In [1]:
from numpy import random

x = random.randint(100)

print(x)

5


### Generate Random Float

#### Generate a random float from 0 to 1

In [2]:
x = random.rand()

print(x)

0.6484467166820345


### Generate Random Array

#### Generate a 1-D array containing 5 random integers from 0 to 100

In [3]:
x=random.randint(100, size=(5))

print(x)

[49 97 67 64 83]


#### Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

In [4]:
x = random.randint(100, size=(3, 5))

print(x)

[[71 35 17  1 42]
 [17 50 29 56 94]
 [10 93 31 48 22]]


#### Generate a 1-D array containing 5 random floats

In [5]:
x = random.rand(5)

print(x)

[0.08258011 0.47006236 0.21674815 0.07457009 0.00816536]


#### Generate a 2-D array with 3 rows, each row containing 5 random numbers

In [6]:
x = random.rand(3, 5)

print(x)

[[0.46414187 0.55804905 0.64700992 0.79717924 0.38131054]
 [0.57288514 0.2719862  0.36290702 0.79639424 0.55289727]
 [0.91183984 0.29038575 0.12885305 0.12928155 0.52167938]]


### Generate Random Number From Array

#### Return one of the values in an array

In [7]:
x = random.choice([3, 5, 7, 9])

print(x)

7


#### Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [8]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 5 7 7 9]
 [5 9 7 9 5]
 [7 5 9 5 3]]
