## NumPy Sorting Arrays

#### Sorting Arrays

In [1]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


#### Sort the array alphabetically

In [2]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


#### Sort a boolean array

In [3]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


### Sorting a 2-D Array

#### Sort a 2-D array

In [4]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
