## Reshaping arrays

### Reshape From 1-D to 2-D

#### Convert the following 1-D array with 12 elements into a 2-D array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D

#### Convert the following 1-D array with 12 elements into a 3-D array

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Can We Reshape Into any Shape?

#### Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error)

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

### Returns Copy or View?

#### Check if the returned array is a copy or a view

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


### Unknown Dimension

#### Convert 1D array with 8 elements to 3D array with 2x2 elements

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays

#### Convert the array into a 1D array

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
